services:
  - type: web
    name: xamSaDeukk
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_AI_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
